### ISSUE TITLE
MovePage with MediaWiki 1.23.2

### ISSUE THREAD

**Issue by theunforgiven89** [eldur/jwbf#51]
Greetings,

Long time user of your library here; I've been using it for almost two years now, and it's absolutely great.

I'm in the process of moving several thousand pages and I thought it would be a good idea to use your library especially since it has the MovePage class.

For some reason, I can't seem to get this class to work for me. Some of the error I get include:

[Thread-3] ERROR net.sourceforge.jwbf.mapper.XmlConverter - unknownerror: Unknown error: "immobile-source-namespace"
<?xml version="1.0"?><api><error code="unknownerror" info="Unknown error: &quot;immobile-source-namespace&quot;" /></api>

^ Fixed when I used MediaWiki.urlEncode(oldtitle) and MediaWiki.urlEncode(newtitle) in my MovePage function call.

AND:

no attribute found for key: movetoken

^ Can't get it fixed.

I read the MovePageTest and the MovePage java doc online, but they offered no clue as to why I'm getting the above error message. I'm pretty nothing is wrong with my LocalSettings.php file...

Is this a known issue with the version of MediaWiki I'm using (1.23.2)? If so, is there any way to fix it other than upgrading my wiki to the latest version? Please help!

**Comment by theunforgiven89** [comment]
Followup: I can't believe it, but I just realized it's not possible to move category pages... My bad.

**Comment by eldur** [comment]
I assume we can close this issue?

**Comment by theunforgiven89** [comment]
We can. I apologize for the inconvenience.
