### ISSUE TITLE
Delete Category Pages

### ISSUE THREAD

**Issue by theunforgiven89** [eldur/jwbf#53]
Greetings,

This isn't exactly an issue, but more of a question.

Is it possible to use this library to delete category pages? If so, how?

Thanks in advance.

**Comment by eldur** [comment]
like normal _pages_ ...
```java
MediaWikiBot bot = new MediaWikiBot(...
...
bot.delete("Category:SomeCategory");
```

**Comment by eldur** [comment]
I assume this was helpful, I'll close this task.
