### ISSUE TITLE
connection through a proxy

### ISSUE THREAD

**Issue by vhilaire** [eldur/jwbf#54]
I'am working behind a proxy. I have found a post on the subject http://sourceforge.net/p/jwbf/feature-requests/20/ but the code is deprecated.

Anyone has an idea ?

Thanks 

Vincent Hilaire

**Comment by eldur** [comment]
Hi @vhilaire, you can define your proxy at bot creation. 

```java
// define a custom apache http client with proxy configuration
CloseableHttpClient apacheHttpClient = HttpClientBuilder.create()
    .setProxy(HttpHost.create("proxy"))
    .build();

// define a actionClient for your wiki bot with your apacheHttpClient
HttpActionClient actionClient = HttpActionClient.builder()
    .withClient(apacheHttpClient)
    .withUrl("http://wiki.url/")
    .withUserAgent("yourBotName", "1.0")
    .build();

// create a new bot with this
MediaWikiBot bot = new MediaWikiBot(actionClient);
bot...
```

I tend to close this issue, or do you have other questions releated to jwbf and proxy configuration?

**Comment by vhilaire** [comment]
Hello,


yes it works, thank you very much.

Vincent
