### ISSUE TITLE
FileUpload uses wrong input for GetApiToken

### ISSUE THREAD

**Issue by leonard84** [eldur/jwbf#61]
The FileUpload uses ` simpleFile.getPath()` which just delegates to `file.getPath()` this causes issues if the path is relative, since relative paths are forbidden.
```uploadTokenAction = new GetApiToken(Intoken.EDIT, simpleFile.getPath());```

For the actual upload it uses the correct title property of `SimpleFile`
``` .param("filename", MediaWiki.urlEncode(simpleFile.getTitle()))```

So all that is to do here is to change 
```uploadTokenAction = new GetApiToken(Intoken.EDIT, simpleFile.getPath());```
to
```uploadTokenAction = new GetApiToken(Intoken.EDIT, MediaWiki.urlEncode(simpleFile.getTitle()));```

**Comment by eldur** [comment]
Sounds good, can you submit a patch?

**Comment by leonard84** [comment]
Done, could you please publish a new release when #62 is merged, it is effectively blocking our use of jwbf.

**Comment by leonard84** [comment]
@eldur great, could you please publish a bugfix release.

**Comment by leonard84** [comment]
@eldur is there anything blocking a bugfix release?

**Comment by eldur** [comment]
holidays 😄

**Comment by leonard84** [comment]
@eldur could you give me an ETA?

**Comment by eldur** [comment]
is released as 3.1.1

**Comment by leonard84** [comment]
thanks
