### ISSUE TITLE
getArticle last revision or cached version?

### ISSUE THREAD

**Issue by benjaminkomen** [eldur/jwbf#63]
I have written a bot using this plugin, but I noticed some strange behaviour. At this point my bot is a bit inefficient, it edits the same article multiple times, i.e.:
1) get article
2) add a string somewhere
3) save article

(some other code)
1) get the same article
2) add a string somewhere
3) save article

But when I access this article the second time, it overwrites the changes made in the first time saving the article. So I thought, it probably accesses a cached version when I try to get the article the second time. Is this true? Can I avoid this by forcing to really get the last revision when requesting an article?

**Comment by benjaminkomen** [comment]
While debugging I found, jwbf generates the following url (just an example):
http://tibia.wikia.com/api.php?action=query&format=xml&prop=revisions&rvlimit=1&rvprop=content%7Ccomment%7Ctimestamp%7Cuser%7Cids%7Cflags&rvdir=older&titles=Burster

If I do an edit and then access that url it gives me an older revision. To get the brand new one I can play with rvstart, e.g. this works:
http://tibia.wikia.com/api.php?action=query&format=xml&prop=revisions&rvlimit=1&rvprop=content%7Ccomment%7Ctimestamp%7Cuser%7Cids%7Cflags&rvdir=newer&titles=Burster&rvstart=2017-02-26T18:35:16Z

**Comment by eldur** [comment]
Feels like an wika related problem - or is it reproducible with plain media wiki?

**Comment by benjaminkomen** [comment]
I'll try to reproduce it with plain media wiki and let you know.
