### ISSUE TITLE
Bug in obtaining multiple pages at once

### ISSUE THREAD

**Issue by benjaminkomen** [eldur/jwbf#68]
In this file: https://github.com/eldur/jwbf/blob/master/src/main/java/net/sourceforge/jwbf/mediawiki/actions/editing/GetRevision.java

I had to remove line 84 which contains ".param("rvlimit", "1")", otherwise I would get an error message when attempting to obtain multiple pages in one query.

I forked this project and re-compiled it (using the maven no-test profile, a lot of tests gave me errors). In this edit: https://github.com/benjaminkomen/jwbf/commit/3e5fdcee814f095253713268ff7850084555fa85 in my fork I "fixed" the bug mentioned in this ticket. I never made a pull request, but since this is only one line of code, maybe you can just fix it for me?

**Comment by ThStock** [comment]
Can you add a test that shows how you obtain multiple pages?

**Comment by eldur** [comment]
Can you add a tests that shows how you obtain multiple pages?

**Comment by benjaminkomen** [comment]
My unit test does (in the @Before method it creates an instance of a MediaWikiBot and logs it in):
```
@Test
    public void testGetArticles() {
        List<String> PAGE_NAMES = Arrays.asList("Dragon", "Bear", "Ferumbras", "Santa Claus");
        List<Article> result = target.getArticles(PAGE_NAMES);

        assertThat(result, hasSize(PAGE_NAMES.size()));
    }
```

The method called is:
```
public List<Article> getArticles(List<String> pageNames) {
        return getArticles(pageNames.toArray(new String[0]));
    }
```

Which calls:

```
public List<Article> getArticles(String[] pageNames) {
        return mediaWikiBot.readData(pageNames).stream()
                .map(sa -> Article.withoutReload(sa, mediaWikiBot))
                .collect(Collectors.toList());
    }
```

Which calls:
```
// TODO 'data' is not very descriptive
  public ImmutableList<SimpleArticle> readData(String... names) {
    return readData(ImmutableList.copyOf(names));
  }
```

Which calls:
```
 // TODO 'data' is not very descriptive
  public ImmutableList<SimpleArticle> readData(ImmutableList<String> names) {
    return getPerformedAction(new GetRevision(names, DEFAULT_READ_PROPERTIES)).asList();
  }
```

Which calls the method I think has a bug (which I commented out):
```
  public GetRevision(ImmutableList<String> names, int properties) {
    this.properties = properties;
    this.names = names;
    // TODO continue=-||
    msg = new ApiRequestBuilder() //
        .action("query") //
        .formatXml() //
        .param("prop", "revisions") //
        .param("titles", MediaWiki.urlEncode(MediaWiki.pipeJoined(names))) //
        .param("rvprop", getDataProperties(properties) + getReversion(properties)) //
        //.param("rvlimit", "1") //
        .buildGet();
  }
```

Current code calls the following url: http://tibia.wikia.com/api.php?action=query&format=xml&prop=revisions&rvprop=content%7Ccomment%7Ctimestamp%7Cuser%7Cids%7Cflags&rvlimit=1&rvdir=older&titles=Dragon%7CBear%7CFerumbras%7CSanta+Claus%20UTF-8

Which returns:
```
<api servedby="ap-s94">
<error code="rvmultpages" info="titles, pageids or a generator was used to supply multiple pages, but the limit, startid, endid, dirNewer, user, excludeuser, start and end parameters may only be used on a single page."/>
</api>
```

My modified working code calls (same url without &rvlimit=1): http://tibia.wikia.com/api.php?action=query&format=xml&prop=revisions&rvprop=content%7Ccomment%7Ctimestamp%7Cuser%7Cids%7Cflags&rvdir=older&titles=Dragon%7CBear%7CFerumbras%7CSanta+Claus%20UTF-8

![working](https://user-images.githubusercontent.com/12815582/34461703-f6dae422-ee31-11e7-91c7-ee0167bd1805.png)

**Comment by benjaminkomen** [comment]
By the way, this is not wikia-related, the same applies to a call to en.wikipedia.org: https://en.wikipedia.org/w/api.php?action=query&format=xml&prop=revisions&rvprop=content%7Ccomment%7Ctimestamp%7Cuser%7Cids%7Cflags&rvlimit=1&rvdir=older&titles=Dragon%7CBear%7CFerumbras%7CSanta+Claus%20UTF-8

which returns:
```
<api servedby="mw1288">
<error code="invalidparammix" info=""titles", "pageids" or a generator was used to supply multiple pages, but the "rvlimit", "rvstartid", "rvendid", "rvdir=newer", "rvuser", "rvexcludeuser", "rvstart", and "rvend" parameters may only be used on a single page." xml:space="preserve">
See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.
</error>
</api>
```
