### ISSUE TITLE
More info on Recent Changes

### ISSUE THREAD

**Issue by ZeroOne3010** [eldur/jwbf#69]
The current `RecentchangeTitles` query is not too useful in itself, as it only returns article titles. The API, however, can return a lot of other information as well, such as article sizes before and after the change, who modified the article, etc. I'd love to have a query that returned all this.

To me it seems that this should be pretty easy: copy `RecentchangesTitles` into a new file named `RecentChanges` and modify the query there. Then make it return a list of new `net.sourceforge.jwbf.core.contentRep.RecentChange` objects and write an integration test for everything.

I might be able to come up with a pull request if you think this would be a good idea and a decent plan.

**Comment by eldur** [comment]
Sounds very good, feel free to send a PR

**Comment by ZeroOne3010** [comment]
@eldur It took a little longer than anticipated, but a pull request has now been submitted. Please review! :smiley_cat:
